# LINEAR ALGEBRA

In [35]:
import numpy as np
from functools import partial
import math

### NB: List for vector is terrible for performance.

In [36]:
# BASIC VECTOR OPERATIONS
def vector_add(v, w):
    return [v_i + w_i for v_i, w_i in zip(v,w)]
def vector_subtract(v,w):
    return [v_i - w_i for v_i, w_i in zip(v,w)]
def vector_sum1(vectors):
    result = vectors[0]
    for vector in vectors[1:]:
        result = vector_add(result, vector)
    return result
def vector_sum2(vectors):
    return reduce(vector_add, vectors)
def vector_sum3(vectors):
    return partial(reduce, vector_add)
def scalar_multiply(c, v):
    return [c*v_i for v_i in v]
def vector_mean(vectors):
    n = len(vectors)
    return scalar_multiply(1/n, vector_sum2(vectors))
def dot(v, w):
    return sum(v_i*w_i for v_i, w_i in zip(v, w))

In [37]:
# VECTOR SPACE
def sum_of_squares(v):
    return dot(v,v)
def magnitude(v): # length of vector
    return math.sqrt(sum_of_squares(v))
def squared_distance(v, w):
    return sum_of_squares(vector_subtract(v, w))
def distance1(v, w):
    return math.sqrt(squared_distance(v, w))
def distance2(v, w):
    return magnitude(vector_subtract(v, w))

In [38]:
# MATRICES
A = [[1,2,3],
     [4,5,6]]
B = [[1,2],
     [3,4],
     [5,6]]
def shape(A):
    numRows = len(A)
    numCols = len(A[0]) if A else 0
    return numRows, numCols
def get_row(A, i):
    return A[i]
def get_col(A, j):
    return [A_i[j] for A_i in A]
def make_matrix(numRows, numCols, entry_fn):
    return [[entry_fn(i,j) for j in range(numCols)] for i in range(numRows)]
def is_diagonal(i, j):
    return l if i==j else 0

### Numpy
**for more, see: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html**

In [39]:
import numpy as np

In [40]:
# BASIC OPERATIONS
A = np.arange(15).reshape(3,5)
    # array([[ 0,  1,  2,  3,  4],
    #        [ 5,  6,  7,  8,  9],
    #        [10, 11, 12, 13, 14]])
print A.shape # row, col
print A.ndim # dimension of matrix
print A.dtype # dtype('int64')
print A.itemsize # length of one array element in bytes.
print A.size # number of cells
print type(A) # numpy.ndarray

(3, 5)
2
int64
8
15
<type 'numpy.ndarray'>


In [41]:
# TYPE SPECIFIED
np.array([[1,2],[3,4]], dtype=complex)

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [42]:
# SET, REVERSE
A = np.arange(10)**3
print A
A[:6:2] = 1000 # equivalent to A[0:6:2], from 0 to 6 position, exclusive, set every 2nd element to -1000
print A
print A[::-1] # reverse A

[  0   1   8  27  64 125 216 343 512 729]
[1000    1 1000   27 1000  125  216  343  512  729]
[ 729  512  343  216  125 1000   27 1000    1 1000]


In [43]:
# FLATTEN
A = np.floor(10*np.random.random((3,4)))
print A
print A.ravel()

[[ 3.  1.  1.  3.]
 [ 1.  6.  6.  4.]
 [ 5.  1.  7.  9.]]
[ 3.  1.  1.  3.  1.  6.  6.  4.  5.  1.  7.  9.]


In [44]:
# RESHAPING
A = np.floor(10*np.random.random((3,4)))
print A
A.resize((4,3))
print A
A.reshape((2,-1)) # 2 row, col automatically calculated.
print A

[[ 6.  5.  8.  4.]
 [ 9.  7.  3.  8.]
 [ 6.  9.  3.  0.]]
[[ 6.  5.  8.]
 [ 4.  9.  7.]
 [ 3.  8.  6.]
 [ 9.  3.  0.]]
[[ 6.  5.  8.]
 [ 4.  9.  7.]
 [ 3.  8.  6.]
 [ 9.  3.  0.]]


In [45]:
# ADVANCED SLICING
A = np.floor(10*np.random.random((2,12)))
print A
print np.hsplit(A,3) # split A into 3 parts, horizontally.
print np.vsplit(A,2) # split A into 2 parts, vertically.
print np.hsplit(A, (3,4)) # split after 3rd and 4th col.

[[ 5.  5.  6.  2.  8.  7.  9.  2.  3.  3.  0.  7.]
 [ 8.  5.  9.  2.  6.  6.  0.  4.  8.  4.  4.  8.]]
[array([[ 5.,  5.,  6.,  2.],
       [ 8.,  5.,  9.,  2.]]), array([[ 8.,  7.,  9.,  2.],
       [ 6.,  6.,  0.,  4.]]), array([[ 3.,  3.,  0.,  7.],
       [ 8.,  4.,  4.,  8.]])]
[array([[ 5.,  5.,  6.,  2.,  8.,  7.,  9.,  2.,  3.,  3.,  0.,  7.]]), array([[ 8.,  5.,  9.,  2.,  6.,  6.,  0.,  4.,  8.,  4.,  4.,  8.]])]
[array([[ 5.,  5.,  6.],
       [ 8.,  5.,  9.]]), array([[ 2.],
       [ 2.]]), array([[ 8.,  7.,  9.,  2.,  3.,  3.,  0.,  7.],
       [ 6.,  6.,  0.,  4.,  8.,  4.,  4.,  8.]])]
